<?php

/**
 * @file
 * Primary module hooks for c2pa module.
 */

 function c2pa_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'c2pa/c2pa';
 }

 function c2pa_theme($existing, $type, $theme, $path) {
  return [
    'c2pa_image_formatter' => [
      'variables' => [
        'item' => NULL,
        'item_attributes' => NULL,
        'url' => NULL,
        'image_style' => NULL
      ]
    ]
  ];
 }

 function template_preprocess_c2pa_image_formatter(&$variables) {
  $variables['image'] = [
    '#theme' => 'image',
  ];
  $variables['image']['#attributes'] = $variables['item_attributes'];

  $item = $variables['item'];

  // Do not output an empty 'title' attribute.
  if (!is_null($item->title) && mb_strlen($item->title) != 0) {
    $variables['image']['#title'] = $item->title;
  }

  if (($entity = $item->entity) && empty($item->uri)) {
    $variables['image']['#uri'] = $entity->getFileUri();
  }
  else {
    $variables['image']['#uri'] = $item->uri;
  }

  foreach (['width', 'height', 'alt'] as $key) {
    $variables['image']["#$key"] = $item->$key;
  }
 }

/**
 * Implements template_preprocess_filter_caption().
 */
function c2pa_preprocess_filter_caption(&$vars) {
  $vars['classes'] .= ' c2pa-wrapper';
  $vars['#attaches']['library'][] = 'c2pa/c2pa';
}
